
# @name signup
POST http://localhost:3000/user/signup 
Content-Type: application/json

{
    "name":"Sill",
    "role":"NORMAL",
    "email":"sill@sill",
    "password":"123456"
}

###

# @name login
POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email":"georg@gmail.com",
    "password":"123456"
}

###

# @name registerBand
POST  http://localhost:3000/band/register 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMWJmYmMzLTM3YjYtNDAyMC04Y2IxLTFhMDUwMGYzYmMyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYwMjU0MSwiZXhwIjoxNjQ3NjAzNzQxfQ.H_YOWdvI_xhj4vrMBOonbOeHqJFEdJSZ0VHbD_Wj7nU

{
    "name":"gun in roses",
    "music_genre":"rock",
    "responsible": "Larissa"
 
}

###

# @name GetInfoBandById
GET  http://localhost:3000/band/byid/30410b2d-d328-4727-a8d4-d5c861507cd2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMWJmYmMzLTM3YjYtNDAyMC04Y2IxLTFhMDUwMGYzYmMyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYzMTE4MCwiZXhwIjoxNjQ3NjMyMzgwfQ.FlsVNMh8-9Nb6paz9tX6sV5EzRE5tENQM1oIYXWcfTE
Content-Type: application/json

###

# @name GetInfoBandByName
GET  http://localhost:3000/band/byname
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMWJmYmMzLTM3YjYtNDAyMC04Y2IxLTFhMDUwMGYzYmMyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYzMTE4MCwiZXhwIjoxNjQ3NjMyMzgwfQ.FlsVNMh8-9Nb6paz9tX6sV5EzRE5tENQM1oIYXWcfTE
Content-Type: application/json

{
    "name":"gun in roses"
}
###

# @name CreatShow
POST http://localhost:3000/show/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMWJmYmMzLTM3YjYtNDAyMC04Y2IxLTFhMDUwMGYzYmMyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYzMTE4MCwiZXhwIjoxNjQ3NjMyMzgwfQ.FlsVNMh8-9Nb6paz9tX6sV5EzRE5tENQM1oIYXWcfTE

{
    "weekDay": "FRIDAY",
    "startTime": 21,
    "endTime": 22,
    "bandId": "99586356-e92a-4770-bb26-5b473630fe73"
}

###

# @name GetShowsByDay
GET http://localhost:3000/show/byday
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNlMWJmYmMzLTM3YjYtNDAyMC04Y2IxLTFhMDUwMGYzYmMyNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYzMTE4MCwiZXhwIjoxNjQ3NjMyMzgwfQ.FlsVNMh8-9Nb6paz9tX6sV5EzRE5tENQM1oIYXWcfTE

{
    "week_day": "sexta"
}


###
